### ISSUE TITLE
git fork -- Permission Denied Public Key

### ISSUE THREAD

**Issue by whatasunnyday** [jingweno/gh#198]
I'm having a problem with using any gh command that interacts directly with my github account. For example, if I was to clone this repository using `gh clone jingweno/gh` and then entered the directory and then tried `gh fork`, it would print the following stack trace. Oddly enough, a fork appears in my list of repositories and a remote is added but I can't push to it.

```
Updating whatasunnyday
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch whatasunnyday
```

**Comment by jingweno** [comment]
This should be fixe din the latest `hub` 2.2.0 release: https://github.com/github/hub/releases/tag/v2.2.0-rc1. Please give it a shot. Note that moving forward `gh` will be merged with `hub` and known as [GitHub CLI](https://github.com/github/hub/issues/718). I'll provide a migration path from `gh` to `hub` in the near future. Please reopen if the problem still exists in `hub`
