### ISSUE TITLE
gh compare (feature-branch)

### ISSUE THREAD

**Issue by dufferzafar** [jingweno/gh#224]
Calling `gh compare` while being on a feature branch could take the branch name automatically.

For eg, If I am on a branch called `docs`, when I call `gh compare` it could excute `gh compare docs`

**Comment by jingweno** [comment]
Closing. Please reopen if you're expecting different behavior. Also please try out `hub` 2.2.0: https://github.com/github/hub/releases/tag/v2.2.0-rc1. Moving forward `gh` will be merged with `hub` and known as [GitHub CLI](https://github.com/github/hub/issues/475).
