### ISSUE TITLE
Don't require GitHub repo to be `origin` remote

### ISSUE THREAD

**Issue by parkr** [jingweno/gh#227]
Hey, I have a repo I backup to GitHub so I have the github repo setup as the `gh` remote. It would be great if `gh` looped through all the remotes and found the one whose host matched the `GITHUB_URL` and used that for the relevant commands. Thoughts?

**Comment by flying-sheep** [comment]
yeah, indeed. same for `gh pull-request`.

for me, the canonical repo is seldomly `origin`, that’s my fork, unless i’m a contributor! i chose `upstream` as a personal convention.

**Comment by flying-sheep** [comment]
so, what names are supported now? gh? upstream? hub?

**Comment by jingweno** [comment]
@flying-sheep The origin names lookup order is [upstream, github and origin](https://github.com/github/hub/blob/1e8f4f4f83c8dc3058ccf0a9d082d553796dc210/github/remote.go#L13). Also [`gh` has been merged into `hub`](https://github.com/github/hub/issues/475). Please move onto `hub` for further feature request.
