### ISSUE TITLE
gh pull-request default message based on local version of base branch, not remote

### ISSUE THREAD

**Issue by Peeja** [jingweno/gh#229]
When I `gh pull-request` it fills in the commit messages of the new commits in the branch, relative to the branch. However, it's not comparing the branch to the remote branch (the actual base), it's comparing it to the local branch with (I think) the same name.

Thus, if I wanted to send a pull request to `origin` for my `new-feature` branch against `master`, it's comparing my branch to `refs/heads/master`, when it should be comparing it to `refs/remotes/origin/master`.

Switching to `master`, pulling the latest from `origin/master`, switching back, and `gh pull-request`ing again shows the expected pre-filled message.

**Comment by jingweno** [comment]
This should be fixed in the latest release of `hub`: https://github.com/github/hub/releases/tag/v2.2.0-rc1. Please give it a shot.
