### ISSUE TITLE
Can't force SSH for GitHub Enterprise

### ISSUE THREAD

**Issue by purinkle** [jingweno/gh#230]
Whenever we try and clone a repo from our GitHub Enterprise instance using

```
GITHUB_HOST=github.example.com gh clone organisation/my_repo
```

We get the following the response

```
Cloning into 'my_repo'...
fatal: remote error:
  GitHub private mode is enabled. Git protocol is disabled. Use authenticated http or ssh access instead.
```

Using the following works fine

```
git clone git@github.example.com:organisation/my_repo
```

Is there any way to force gh to use ssh?

**Comment by jingweno** [comment]
This should be fixed in the latest release of `hub`: https://github.com/github/hub/releases/tag/v2.2.0-rc1. Note that `gh` has been merged with `hub` and will be known as [GitHub CLI](https://github.com/github/hub/issues/475).
