### ISSUE TITLE
How do I build GH on Windows? or is there a windows prebuilt for 2.1.0?

### ISSUE THREAD

**Issue by fcassirer** [jingweno/gh#231]
I'd like to build GH on Windows, is there a how-to?  There doesn't appear to be a 2.1.0 version prebuilt in the release downloads here.

Thanks!
-Fred Cassirer

**Comment by jingweno** [comment]
Please try out a 2.2.0 release from https://github.com/github/hub/releases/tag/v2.2.0-rc1. [`gh` will be known as GitHub CLI](https://github.com/github/hub/issues/475) and has been merged to `hub`. Closing.
