### ISSUE TITLE
Is this deprecated in favor of hub?

### ISSUE THREAD

**Issue by jeffbyrnes** [jingweno/gh#235]
No indication, but my understanding is that this tool has been deprecated in favor of [github/hub](https://github.com/github/hub).

Is that so? Perhaps some indication in the README would be good?

**Comment by jingweno** [comment]
@jeffbyrnes `gh` is not deprecated until `hub` [2.2.0](https://github.com/github/hub/releases) is released. However there's indeed something on the README:

> Current version is v2.1.0. [Moving forward gh will be known as GitHub CLI](https://github.com/github/hub/issues/475).

**Comment by jeffbyrnes** [comment]
Derp. Sorry about missing that, thanks for responding!

**Comment by jingweno** [comment]
No worry! Thanks for the interests in the project!
